### ISSUE TITLE
Error al grabar en el logger.

### ISSUE THREAD

**Issue by sastremari** [SIU-Toba/framework#132]
Error al grabar en el logger, da error al armar el mensaje. 
el objeto es ef_editable_fecha es obligatorio y si lo dejamos sin llenar al procesar no muestra el mensaje en pantalla 'Fecha de débito es obligatorio.  
El mensaje que larga en pantalla es **'Se produjo un error en la validacion del ef, revise el log '**
y tambien deja el siguiente mensaje:
```
Fatal error: Uncaught Error: Object of class pilaga_ef_editable_fecha could not be converted to string in /usr/local/app/vendor/siu-toba/framework/php/nucleo/lib/toba_basic_logger.php:301 Stack trace: #0 /usr/local/app/vendor/siu-toba/framework/php/nucleo/lib/toba_logger.php(282): toba_logger->armar_mensajes() 
#1 /usr/local/app/vendor/siu-toba/framework/php/nucleo/lib/toba_logger.php(272): toba_logger->guardar_en_archivo() 
#2 /usr/local/app/vendor/siu-toba/framework/php/nucleo/toba_nucleo.php(122): toba_logger->guardar() 
#3 /usr/local/app/www/aplicacion.php(28): toba_nucleo->acceso_web() 
#4 {main} thrown in /usr/local/app/vendor/siu-toba/framework/php/nucleo/lib/toba_basic_logger.php on line 301
```

**Comment by enfoqueNativo** [comment]
@sastremari fijate si el PR te funca, intente asignarte para review pero no pude.
